apiVersion: v1
kind: ConfigMap
metadata:
  name: grt-config
data:
  database-host: "grt-mssql"
  database-port: "1433"
  database-name: "GrtTorchBearer"
---
apiVersion: v1
kind: Secret
metadata:
  name: grt-secrets
type: Opaque
stringData:
  database-connection: "Server=grt-mssql,1433;Initial Catalog=GrtTorchBearer;User Id=sa;Password=GrtBearer@2024!;"
  jwt-secret: "your-super-secret-jwt-key-min-32-chars-change-in-production"
  encryption-key: "your-encryption-key-min-32-chars-for-aes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi